"""add description column to donations

Revision ID: efecb0808de5
Revises: d29705b5a40d
Create Date: 2025-04-21 08:17:51.893328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efecb0808de5'
down_revision = 'd29705b5a40d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
